CREATE SEQUENCE SEQ_PAISES_ID;
CREATE SEQUENCE SEQ_ESTADOS_ID;
CREATE SEQUENCE SEQ_CIDADES_ID;
CREATE SEQUENCE SEQ_PESSOAS_ID;
CREATE SEQUENCE SEQ_PESSOAS_ENDERECOS_ID;
CREATE SEQUENCE SEQ_PESSOAS_TELEFONES_ID;

CREATE TABLE PAISES (
	ID INTEGER NOT NULL DEFAULT NEXTVAL('SEQ_PAISES_ID'),
	DESCRICAO VARCHAR (255) NOT NULL,
	CONSTRAINT PK_PAISES PRIMARY KEY (ID)
);

CREATE TABLE ESTADOS (
	ID INTEGER NOT NULL DEFAULT NEXTVAL('SEQ_ESTADOS_ID'),
	ID_PAIS INTEGER NOT NULL,
	DESCRICAO VARCHAR(255) NOT NULL,
	CONSTRAINT PK_ESTADOS PRIMARY KEY (ID),
	CONSTRAINT FK_ESTADOS_PAISES FOREIGN KEY (ID_PAIS) REFERENCES PAISES(ID)
);

CREATE TABLE CIDADES (
	ID INTEGER NOT NULL DEFAULT NEXTVAL('SEQ_CIDADES_ID'),
	ID_ESTADO INTEGER NOT NULL,
	DESCRICAO VARCHAR(255) NOT NULL,
	CONSTRAINT PK_CIDADES PRIMARY KEY (ID),
	CONSTRAINT FK_CIDADES_ESTADOS FOREIGN KEY (ID_ESTADO) REFERENCES ESTADOS(ID)
);

CREATE TABLE PESSOAS (
	ID INTEGER NOT NULL DEFAULT NEXTVAL('SEQ_PESSOAS_ID'),
	NOME VARCHAR(255) NOT NULL,
	CPF VARCHAR(14),
	DT_NASC DATE,
	TIPO_PESSOA VARCHAR(20),
	CONSTRAINT PK_PESSOAS PRIMARY KEY (ID)
	);

CREATE TABLE PESSOAS_ENDERECOS (
	ID INTEGER NOT NULL DEFAULT NEXTVAL('SEQ_PESSOAS_ENDERECOS_ID'),
	ID_PESSOA INTEGER NOT NULL,
	ID_CIDADE INTEGER NOT NULL,
	DESCRICAO VARCHAR(255) NOT NULL,
	NUMERO VARCHAR (5),
	BAIRRO VARCHAR(50),
	CONSTRAINT PK_PESSOAS_ENDERECOS PRIMARY KEY (ID),
	CONSTRAINT FK_PESSOAS_ENDERECOS_PESSOAS FOREIGN KEY (ID_PESSOA) REFERENCES PESSOAS(ID),
	CONSTRAINT FK_PESSOAS_ENDERECOS_CIDADES FOREIGN KEY (ID_CIDADE) REFERENCES CIDADES(ID)
);

CREATE TABLE PESSOAS_TELEFONES (
	ID INTEGER NOT NULL DEFAULT NEXTVAL('SEQ_PESSOAS_TELEFONES_ID'),
	ID_PESSOA INTEGER NOT NULL,
	DESCRICAO VARCHAR(255),
	NRO_TELEFONE VARCHAR(15),
	CONSTRAINT PK_PESSOAS_TELEFONES PRIMARY KEY (ID),
	CONSTRAINT FK_PESSOA_TELEFONES FOREIGN KEY (ID_PESSOA) REFERENCES PESSOAS(ID)
);

ALTER SEQUENCE SEQ_PAISES_ID
OWNED BY PAISES.ID;

ALTER SEQUENCE SEQ_ESTADOS_ID
OWNED BY ESTADOS.ID;

ALTER SEQUENCE SEQ_CIDADES_ID
OWNED BY CIDADES.ID;

ALTER SEQUENCE SEQ_PESSOAS_ENDERECOS_ID
OWNED BY PESSOAS_ENDERECOS.ID;

ALTER SEQUENCE SEQ_PESSOAS_ID
OWNED BY PESSOAS.ID;

ALTER SEQUENCE SEQ_PESSOAS_TELEFONES_ID
OWNED BY PESSOAS_TELEFONES.ID;



