/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;
public class FrameMenu extends javax.swing.JFrame {

    public FrameMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuCadastro = new javax.swing.JMenu();
        itemPais = new javax.swing.JMenuItem();
        itemEstado = new javax.swing.JMenuItem();
        itemCidade = new javax.swing.JMenuItem();
        itemPessoa = new javax.swing.JMenuItem();
        itemEndereco = new javax.swing.JMenuItem();
        itemTelefone = new javax.swing.JMenuItem();

        jMenu3.setText("jMenu3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MyWater - Alpha v0.0.1");

        menuCadastro.setText("Cadastros");

        itemPais.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        itemPais.setText("Paises");
        itemPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemPaisActionPerformed(evt);
            }
        });
        menuCadastro.add(itemPais);

        itemEstado.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        itemEstado.setText("Estados");
        itemEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemEstadoActionPerformed(evt);
            }
        });
        menuCadastro.add(itemEstado);

        itemCidade.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        itemCidade.setText("Cidades");
        itemCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCidadeActionPerformed(evt);
            }
        });
        menuCadastro.add(itemCidade);

        itemPessoa.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        itemPessoa.setText("Pessoas");
        itemPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemPessoaActionPerformed(evt);
            }
        });
        menuCadastro.add(itemPessoa);

        itemEndereco.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        itemEndereco.setText("Endereços");
        itemEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemEnderecoActionPerformed(evt);
            }
        });
        menuCadastro.add(itemEndereco);

        itemTelefone.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        itemTelefone.setText("Telefones");
        itemTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemTelefoneActionPerformed(evt);
            }
        });
        menuCadastro.add(itemTelefone);

        jMenuBar1.add(menuCadastro);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemPaisActionPerformed
        // TODO add your handling code here:
        DialogPais dialogPais = new DialogPais(this, rootPaneCheckingEnabled);
        dialogPais.setVisible(true);
    }//GEN-LAST:event_itemPaisActionPerformed

    private void itemEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemEstadoActionPerformed
        // TODO add your handling code here:
        DialogEstado dialogEstado = new DialogEstado(this, rootPaneCheckingEnabled);
        dialogEstado.setVisible(true);
    }//GEN-LAST:event_itemEstadoActionPerformed

    private void itemCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCidadeActionPerformed
        // TODO add your handling code here:
        DialogCidade dialogCidade = new DialogCidade(this, rootPaneCheckingEnabled);
        dialogCidade.setVisible(true);
    }//GEN-LAST:event_itemCidadeActionPerformed

    private void itemPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemPessoaActionPerformed
        // TODO add your handling code here:
        DialogPessoa dialogPessoa = new DialogPessoa(this, rootPaneCheckingEnabled);
        dialogPessoa.setVisible(true);
    }//GEN-LAST:event_itemPessoaActionPerformed

    private void itemEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemEnderecoActionPerformed
        // TODO add your handling code here:
        DialogPessoaEndereco dialogPessoaEndereco = new DialogPessoaEndereco(this, rootPaneCheckingEnabled);
        dialogPessoaEndereco.setVisible(true);
    }//GEN-LAST:event_itemEnderecoActionPerformed

    private void itemTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemTelefoneActionPerformed
        // TODO add your handling code here:
        DialogPessoaTelefone dialogPessoaTelefone = new DialogPessoaTelefone(this, rootPaneCheckingEnabled);
        dialogPessoaTelefone.setVisible(true);
    }//GEN-LAST:event_itemTelefoneActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itemCidade;
    private javax.swing.JMenuItem itemEndereco;
    private javax.swing.JMenuItem itemEstado;
    private javax.swing.JMenuItem itemPais;
    private javax.swing.JMenuItem itemPessoa;
    private javax.swing.JMenuItem itemTelefone;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuCadastro;
    // End of variables declaration//GEN-END:variables
}
